# Generated by Django 2.2.12 on 2020-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200506_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.CharField(default='8c09b3654bcf41eaa07a946710bf6346', max_length=36),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(default='8a4d7bffadfd4480ab03d20e4e78398a', max_length=36),
        ),
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.CharField(default='8ac081df28164aea813b9278c500deda', max_length=36),
        ),
    ]
