# Generated by Django 2.2.12 on 2020-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200506_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.UUIDField(default='845d87f34a56474c8b6ec6993495fa31'),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.UUIDField(default='d37b36e771cc49c59914348d2eac7403'),
        ),
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.UUIDField(default='a830caf53d1947dfab091218c9ce5753'),
        ),
    ]
