# Generated by Django 2.2.12 on 2020-05-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200506_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.CharField(default='5ef986ebcac641b2b49b04cf038bc958', max_length=32),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(default='0feab6dac86e4fd38e05bb081d16ac38', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.CharField(default='5b5ad34ad40d4f66b7babe596d34cb35', max_length=32),
        ),
    ]
