# Generated by Django 2.2.12 on 2020-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200516_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.CharField(default='00ed62ad3f254fdbb366f66fd9e7d956', max_length=32),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(default='6faac65b272349dca51212fb15e3d31e', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.CharField(default='2db5b1478a224413a457ee5abcf01c93', max_length=32),
        ),
    ]
