# Generated by Django 2.2.12 on 2020-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200627_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.CharField(default='eeb402e88e4741dbb41232c83977f6ec', max_length=32),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(default='5f9d514e59e34f8887f82d7f271d267b', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.CharField(default='bc1555f2caab4c4eae940d1cf7e01b04', max_length=32),
        ),
    ]
