# Generated by Django 2.2.12 on 2020-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200627_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.CharField(default='d5cdd0d7290e47339356efeee8d4c863', max_length=32),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(default='a72e14503bff4bf6ad5b19a16a7873bf', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.CharField(default='58c147383e684d5080fe9bf8ced4cd0b', max_length=32),
        ),
    ]
