# Generated by Django 2.2.12 on 2020-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200627_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.CharField(default='df739c0196de449d9b8d1dfe26bb6faa', max_length=32),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(default='6524ae50e0f34e31b8657d0bc2b4736f', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.CharField(default='7705657637cf48eb88f4050559d61618', max_length=32),
        ),
    ]
